# JDBC?????????
spring.datasource.driver-class-name = org.h2.Driver
# ????????????jdbc:h2:?+????????
spring.datasource.url = jdbc:h2:~/taskdb
# ?????????????
spring.datasource.username = gihyo
# ?????????????
spring.datasource.password = gihyodb
# SQL??????????????????????????always:?????embedded?????DB????????never???????
spring.datasource.initialization = mode = always
# H2???????????????(true?false)
spring.h2.console.enabled=true